// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Index, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Index, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 184);
    lv_obj_set_height(ui_Container7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_Panel1, 183);
    lv_obj_set_height(ui_Panel1, 192);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_value_arc = lv_arc_create(ui_Panel1);
    lv_obj_set_width(ui_power_value_arc, lv_pct(100));
    lv_obj_set_height(ui_power_value_arc, lv_pct(100));
    lv_obj_set_x(ui_power_value_arc, 0);
    lv_obj_set_y(ui_power_value_arc, 6);
    lv_obj_set_align(ui_power_value_arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_power_value_arc, 0, 20000);
    lv_arc_set_value(ui_power_value_arc, 2000);

    lv_obj_set_style_arc_color(ui_power_value_arc, lv_color_hex(0xF1C40F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_power_value_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_power_value_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_power_value_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label1, "กำลังไฟฟ้า");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Kanit22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power_value_label = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_power_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_power_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_power_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_power_value_label, "2000");
    lv_obj_set_style_text_font(ui_power_value_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 26);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "W");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_Panel6, lv_pct(100));
    lv_obj_set_height(ui_Panel6, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label17, "พลังงานไฟฟ้า");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Kanit22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Panel6);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, LV_SIZE_CONTENT);   /// 274
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_energy_value_label = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_energy_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energy_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_energy_value_label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_energy_value_label, "1000");
    lv_obj_set_style_text_font(ui_energy_value_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label16, "kWh");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 274);
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 296
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel2, 130);
    lv_obj_set_height(ui_Panel2, 130);
    lv_obj_set_x(ui_Panel2, 193);
    lv_obj_set_y(ui_Panel2, 3);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltage_value_arc = lv_arc_create(ui_Panel2);
    lv_obj_set_width(ui_voltage_value_arc, lv_pct(100));
    lv_obj_set_height(ui_voltage_value_arc, lv_pct(100));
    lv_obj_set_x(ui_voltage_value_arc, 0);
    lv_obj_set_y(ui_voltage_value_arc, 6);
    lv_obj_set_align(ui_voltage_value_arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_voltage_value_arc, 0, 220);
    lv_arc_set_value(ui_voltage_value_arc, 220);

    lv_obj_set_style_arc_color(ui_voltage_value_arc, lv_color_hex(0x2ECC71), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_voltage_value_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_voltage_value_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voltage_value_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label4, "แรงดัน");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 2);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_voltage_value_label = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_voltage_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltage_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltage_value_label, 0);
    lv_obj_set_y(ui_voltage_value_label, 2);
    lv_obj_set_align(ui_voltage_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltage_value_label, "220");
    lv_obj_set_style_text_font(ui_voltage_value_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 26);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "V");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel3, 130);
    lv_obj_set_height(ui_Panel3, 130);
    lv_obj_set_x(ui_Panel3, 331);
    lv_obj_set_y(ui_Panel3, 2);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_current_value_arc = lv_arc_create(ui_Panel3);
    lv_obj_set_width(ui_current_value_arc, lv_pct(100));
    lv_obj_set_height(ui_current_value_arc, lv_pct(100));
    lv_obj_set_x(ui_current_value_arc, 0);
    lv_obj_set_y(ui_current_value_arc, 6);
    lv_obj_set_align(ui_current_value_arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_current_value_arc, 2);

    lv_obj_set_style_arc_color(ui_current_value_arc, lv_color_hex(0x3498DB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_current_value_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_current_value_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_current_value_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label7, "กระแส");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 2);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_current_value_label = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_current_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_current_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_current_value_label, 0);
    lv_obj_set_y(ui_current_value_label, 2);
    lv_obj_set_align(ui_current_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_current_value_label, "1.2");
    lv_obj_set_style_text_font(ui_current_value_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 26);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "A");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel4, 130);
    lv_obj_set_height(ui_Panel4, 130);
    lv_obj_set_x(ui_Panel4, 331);
    lv_obj_set_y(ui_Panel4, 2);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_frequency_value_arc = lv_arc_create(ui_Panel4);
    lv_obj_set_width(ui_frequency_value_arc, lv_pct(100));
    lv_obj_set_height(ui_frequency_value_arc, lv_pct(100));
    lv_obj_set_x(ui_frequency_value_arc, 0);
    lv_obj_set_y(ui_frequency_value_arc, 6);
    lv_obj_set_align(ui_frequency_value_arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_frequency_value_arc, 0, 50);
    lv_arc_set_value(ui_frequency_value_arc, 50);

    lv_obj_set_style_arc_color(ui_frequency_value_arc, lv_color_hex(0x8E44AD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_frequency_value_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_frequency_value_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_frequency_value_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label10, "ความถี่");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, 2);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_frequency_value_label = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_frequency_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_frequency_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_frequency_value_label, 0);
    lv_obj_set_y(ui_frequency_value_label, 2);
    lv_obj_set_align(ui_frequency_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_frequency_value_label, "50");
    lv_obj_set_style_text_font(ui_frequency_value_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, 26);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Hz");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel5, 130);
    lv_obj_set_height(ui_Panel5, 130);
    lv_obj_set_x(ui_Panel5, 331);
    lv_obj_set_y(ui_Panel5, 2);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pf_value_arc = lv_arc_create(ui_Panel5);
    lv_obj_set_width(ui_pf_value_arc, lv_pct(100));
    lv_obj_set_height(ui_pf_value_arc, lv_pct(100));
    lv_obj_set_x(ui_pf_value_arc, 0);
    lv_obj_set_y(ui_pf_value_arc, 6);
    lv_obj_set_align(ui_pf_value_arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_pf_value_arc, 95);

    lv_obj_set_style_arc_color(ui_pf_value_arc, lv_color_hex(0x2C3E50), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_pf_value_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pf_value_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pf_value_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label13, "PF");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Panel5);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 2);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pf_value_label = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_pf_value_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pf_value_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pf_value_label, 0);
    lv_obj_set_y(ui_pf_value_label, 2);
    lv_obj_set_align(ui_pf_value_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pf_value_label, "0.95");
    lv_obj_set_style_text_font(ui_pf_value_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}
