// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_power_value_arc;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_power_value_label;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_energy_value_label;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_voltage_value_arc;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_voltage_value_label;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_current_value_arc;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_current_value_label;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_frequency_value_arc;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_frequency_value_label;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_pf_value_arc;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_pf_value_label;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Kanit22);
LV_FONT_DECLARE(ui_font_Kanit18);
LV_FONT_DECLARE(ui_font_Kanit18);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
